version: '3'

services:

  db:
    image: postgres:15
    container_name: db_education
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: education
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5435:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      app_net:

  education:
    build: .
    container_name: education_container
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8001:8000'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/copy
    networks:
      app_net:





networks:
  app_net:

volumes:
  postgres_data:


