# Generated by Django 4.2.4 on 2023-08-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ('-created_at',), 'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
    ]
