# Generated by Django 4.2.4 on 2023-08-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='courses',
            field=models.ManyToManyField(to='education.course', verbose_name='курсы'),
        ),
    ]
